---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-api-key
  namespace: default
spec:
  encryptedData:
    api-key: AgAT3o/MblFRn8kp5i5PQVsrpjlEjg1RocNOLx1DLljjMBatRU5OVCWYqT1QPlc+gETvlzX1rkOXWj9idcl9GrApl+A/QhuRQJ4jaf6i9RSdNMiTskB8dk211EZtu7QATtDyivQ+6bZN9H1xEmcM6uvWkBpwFg9kpyBfEYnqrDrZPMTIcQJpvcBCqLhg6kWuEE6cFuU6FESdtxuXwbIcNpjFfhRctjbnzeMBC5KCZKp/b7isEfPt2O2SNFuRB55Y2ltNSpUVBLUt8ExfMBq2TKqRudZ6lsJgj25hSs/EoLN1rBSHK9XHgMj57SvFg5kjeRa6Q2f0WOywiQL0qhG0mBCZoccBqsQHaZtt5rYYSJHlfJ+1tkFEWhRp80B83I6yZkb67DRBrRqR1BwTucYKtKCEZ6d5Xv4IUrCYQqlHI0mTewRv3KfvUXkGkrX2rA3w8dQ4EyjHppUHQgqRLsT9I59UcP8Pfz6FizxBfQgOsvK68vewL8p7JwQSpu9WMtIKXLtG5JqO3AA8X4wGD/TpjyARl4gLsJNqWAySRYEf6q+rNJ4aeZnxxfiHh4f2WbWmN+PmnMCHBSR1+/jq7RlkyQpodUpGp6xMMtBFyqUhSshcYchPX5ILxvAAOtiwTEhDZVn73rABLlp4o+AeKQEsPmukFI/47qcilvZ1pJwAoKj3zw0BDKpvTOaUUjT9fZMhWwcKJRu2jLdJ+Q7JqaAAGc2lmHKa6HPdIP3C64Q8kxNevyQ9Mb1reZ8=
  template:
    metadata:
      name: google-api-key
      namespace: default
    type: Opaque
