---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notify-secrets
  namespace: default
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgBZgIovXkpqp/Uuw0f73eg5kfoVSSnXsA7mbYJyD6uElxIWvs2vLqwwDqv6TrM9/wldaX9Jj8Z2/9SEJP67SnO6ksgN5gEWYvY5IJts2bTA8kWeY/ElkrjmmrL4wZsU8gx5/b/8c4yOjqdoME8U5QE/uNKHBhysvgKpSHPkUf9wePXsHXvJXMICug2JKnVBPJoZ8IhC3poz4eSTSvyEXb21Y84WKu7mbKqpnvqAmEUoHZPPnm6VrzzZ+lEn4PIf2fCkXmEyK4z/A9Tgh+jGX3gKdvLeGD7KqVzaiPB2UjZf7H/YwyxYXlB25dMkdeTI2i9ae2Y9ntSaWURFR5Bo5Xr4Wfd9tMddCrVwhASoZr5crfQHWBPh5Iuw5Ohmk0UqYxOOOWLFdAaSM0uv/h7my2M9Lw1o20fzjLFMEoERajanklEb72bA0x/F8YZ9uf/kuVqXTy1qs9r3+cOXGexhjwDpUKuXFKds+K7lFZCd0kPe1w2C/nrZPbNHS/KYn6vxyBiiUn8lB+mhmjnLDvEZvrGmAHdLY64R7Nz++8wo9IAbYSg04H2ooc1C9vAfFdlHQQVdrB2Mj9pWf7Xy473a7y2r+lA3ghOlzB5ePsr/vgAFLjlZhqsWsuqMGwpi5mEC74lPhaNnhoYu1DuatmlKkobITdrx5z4mE3K8Kt2dQP3dAb4OZdQxRddGndUBF+mET9srKg9LwRSdIZgBjm2Ffa/Ycke3sQWl/IkvSita75a4UB4pOCJhOiqVxieev9TI3/bBqcWkN0dgu2JFUj3RorNkeqNRXFHCvyb55x5vrZGMXPw=
  template:
    metadata:
      name: notify-secrets
      namespace: default
    type: Opaque
