---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCLRpnhj8dlmuNI0xdEG8ayOsZ53r0ibt/fv0528cak1T3Li3EQlxQm4c9rVCbOsaxv+bNM1aFezd26ABiJHILScWSrrd609Q4H3/aaFqsvgQWDeaEX/SyBi1d8Gn3gJINITfTywSu5dofxWWBB8u3NrBK9U1oRK3Gd3f0qwbY9gpCMFMcYBOIyYNdepKjAgGgplyE0cLqFcTnYRIyTN+DwFtRhMxHse5qEc4uN7ydjwOjqD9xUrZi4GjCJS+c1RmtFHpI+OMiA6vhLcSa4/6iMVsJJw3mAqa1ChZ2Ha2cjki2W2wXDjPQsbqsQYd0baRIbZmG03eO/DyZT+ZiQFJ0uWuAjnTtGfERm5aabjeRjoMhvqVvfFDKbNH3jgyRXwFU7pmBRjr9TY7UIN0GRvfcSnqUT4hzHlJeyKeLsy3p72N4+k/vCCHx2stYqvQ27ZSQbWL6VENWSVOVqA+pJ+NPgly03JuSq4ng2V7E5X712i8gMaJcvbKlatCM8YlqUgE14NwCDMm5/0M5muN9ZVv+b5Pe4FGzFwdyAjV3GlgzTfnsQ1FAJi02nJwgL+nTJ+TG8CS7kTNapGQtsOIILKMgIbqSdr48Kl4ANdV3ROlXdQy5u5mjvZ0dPK/1N6BloNzG5jrWpg59qSJ1qYLJgT4gUgESAn+SIlFe81So2y9qLJn1qi9ahPBgTP8U6n84DaVdrJ4SxFf0jSzLK0qouXrTBL1mOidiDX8OCitN81bnxue75++Mgx6JSOGBvOtUeaCDvztcF4lIsLGkM0LBc1q/Ii6dHbOmVYemB9BKDB5etxNGXWrFSYIDQrO8LzKdsF8vfOed4fVngwrLd+9FRPBBvlhfg0EA66TcEvLPVqoxGii0VaWdrKZiPVB3uVMQFnZBWPvhauajQ+yElqBoYqWL7OKoA4EDHaQkj9IAyZKZTXBM3zO6u/8FIVBtjGmnBhlDtU2nHbuz3HGiBWKZvrw5VHImDSPQTIL0mMZG8qfA4B3He
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
