---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notify-secrets
  namespace: default
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgB6xnJcvwvM69JMIaasol4XoWbCJWf+hWw5vp9lgsc3P9mc4lNHB02ZAy/KDiH1JEsLT4l6BD11yHpB2qTo+9l3V2C0JlgNc7nauzq2dxRYTtGlNkkz/fVhqSoT7eU4EUStiKDtFk0gG6RbhyL9Io9VYIWMzen4dlkKZr3CLUNAmhZ7RCH2NETif6QykYv74+ByNGteN5wlBxaA/56FT+hCcrmeRyEltQF29gBKo6MLkIcqvrs40aZmhDyv4wvkiupol1hs/3WL6x3cUZtXlUoQSy7Uq8TWpCFiFdyGH0KQH/pYdH0+SAcDOCPoJf1QO9+lxEHcFznXl8uMdvdn1TlREJc45iA9ZGT4T5skcA1vo1Z5cW1v0ESTms0I630tdvlSoag/vhzfiH28lpfREq2ra6T3sEVhbPv5uiHeYFBweUj14rHcxZyJ3mKS+5isaw1etZWd1RAGJULiVOINSnzinX3P3Bei0bCAEyWWuPokCwzJ2Ci8Tptjg9s/UIrt2ic5K0wcyAxWaM695uWyDkulCV4VJ2WgI1qk5LmFR5WKLYe/s97Old737+Z0PwV7yjeplI2sStP/0McJlYs3z6y2LH2A1iIXkrZVAu57A7tdFKsUBQ0oXnjmj6d1lZb5ioMhTbzHQOIu7vP2CHS0llCRm1RavA160fbr89aWwD6cLQ3SLDY225h9mAkpVkPLVQLUmoKuoUmdmgnJ4dUBrKoLhXeDrkioj7a3tI3CoxAkxGTlTAijg0KUxmoBOU18yS2K5z457iG4WU01WsAJnpKL1QkXf+/I+r7j23RZYBz5lT4=
  template:
    metadata:
      name: notify-secrets
      namespace: default
    type: Opaque
