---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCV8KCwqPELOUUzDw0H73sj4Ji3PZ27PxAXfmgga5eonq7nZNwKoYjKzbEcog24Bp20M9pow4vd5NJgN0jZtOROcnR2ueddXU40J7HFhIksc8ecF+zPUDhxjnryDpbyS+PC1Ecm9c8XGgg7ph+IhwO4IbgePhIIi8s1Rk4ggDdDGvNbLr4yx/mCMCrSE0Z8YnQ/6ixglrkltmq3dSyd6unCFELUEEN3i4/nv0vL3OTstlsoRHaYX4Nt43BQeVHSmshDQSdRYgnoj/SpAC9VH8ELU8ub4PpAM7JwSq32a+WYH+FtIRbnVkv6K5Hv3BYfzWfncvk3jBiL9TZsooetpiJc7QL6snOir3SP+yvSfq9wfV2Bfpz4tbmpMx+OwnRwNGEo/OkEqB6aml87ECoFrCdknxIEZhn0rMvxRjm+BvvAz+Tjy70/BBt6f+L2WWZcppWpEKi0fnQboHbdSGZY4tkWAEDzqfj03zdeM3VwPCnQJNg+ki2wxhaWA+beIT2NssYMdqZkJTAL4Nvxn/GHWqrKsM8//bJh7bG3IvcKFxxflXMJLW+Ck2KTOkvd75SqsjbfitoPwO8R2VHRlHTSm8FWbLR6e6aEulX3efRrKHsdITGXvGz8r29fnm+Gkj7BUZnuTyfBOF3mF+M74yYp7pBJQ8qyA3TpKhXW2HTos7N/fqyVc52os47iQ42tyn7TmJvTt1DUiycZvLZ5dibua1vS8/uCV/5/dVA2fnuvoimm38gS+7deSpXJiLcUb9IWN/8f+Do2po1HVr3F0aJNpgiQ6CcSSGnuzdUDVnBqdXS4/KE7OKBH7LKtTyyWWBWJd2CFOWocNAYkWZDCEdnmsaRfL2kfxAzXjUoa77br9kOHTwpfAn4H0Hb9Klu/9drxFFzAvAs+rjQawWJdsowgtXfYpjzpSMG+owPvykQ0kdXb8TqlIMjLUSBN0lIlLfFch6fuyg4tlE+ifuHJfND0TX3RQ+A1F8X3gQCpv0Kph5j+h9mg
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
