---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-api-key
  namespace: default
spec:
  encryptedData:
    api-key: AgBtxmTUZFbIHGnPbBjStoMK5PuKG+V/EBZLQPl5EanUMiQMfMxNNlju6HPizj+WsXYFAt5dbnxSlkkcgbCkT++Y8sVKHqu1eBkWYxjQt1odIAVTw3U9czP4qGxsnco3NqddcR+NqR4pOJtltxILLgN8QdL5diufuHuduTcTeD7a3OttyyINfSviQWC0PXs5mQ+ydFplbTNTollnHy3ak1D4vnfzFUbbY3xYgfu51K38UkgeoNCGXgGOwMFnvxclwplE1TG5mihOpztIFslvNXn9xrbuq2zykSVo9p566F4Hwt90D4zrFBUFMhMudwfkgLzvE/PRGYnj6Z1U6qd80L9saV+H73AUtUYx0cTIvASyRcKvU3fAYqT+4A6X/UhwFpUOBCianC86RhGD6O5t+1V+UFDM05b5gOM4NMsFIaWqqH5PfqAQeYz6zxzmOkoX+ENvBakiPx41jzUxN9XnTyaUDSstUBFurxuyve2RBhAKSpoGknz0bGzOvUlqQtb+dXcqqYw4SV8fq6wZuDrn2U+elvFe4pzcAUB6CIG1QYJAMU5xRbTR7D1RBOSm0LQAOpkb6IeAneBl/i2IlePZh9G4lSLO3EJ/8pDd3C2w4JdTdBY9MkdtPAfEfXftJUE4OShF9HSN+74yAdvxXX+6uAHpm4crU7T0IO73XHSv5HtoJ8WeAJ9DmgTUlLxbE4wlByYq79n59LrOTp4wHoS71YK2d341Ugka36TcncVz/8ruiKHFkp6Qtu4=
  template:
    metadata:
      name: google-api-key
      namespace: default
    type: Opaque
