openapi: 3.0.0
info:
  title: Youtube tracker API
  description: API for retrieving information about Youtube channels
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /status:
    get:
      summary: current service state
      description: Returns a Status object
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /youtube/channel:
    post:
      description: Store new Youtube channel
      requestBody:
        description: Payload for example
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/YoutubeChannel'
      responses:
        201:
          description: Successfully stored
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoutubeChannel'
        409:
          description: Already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoutubeChannel'
  /youtube/channel/{id}:
    get:
      summary: Get Youtube Channel by ID
      description: Returns a YoutubeChannel object by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the channel
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoutubeChannel'
        '404':
          description: Not found
          content: {}
  /youtube/channel/{id}/statistics:
    get:
      summary: Get Youtube Channel statistics by ID
      description: Returns a YoutubeChannel statistics by ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the channel
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoutubeChannelStatistics'
        '404':
          description: Not found
          content: { }
  /youtube/channels:
    get:
      description: Get all Youtube channels
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            format: int
            minimum: 1
          required: false
          description: Page number (starts from 1)
        - in: query
          name: page_size
          schema:
            type: integer
            format: int
          required: false
          description: Number of items to return per page
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/YoutubeChannelList'
  /schedule:
    post:
      description: Initiate statistics generation
      responses:
        200:
          description: Task started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatGenerationStarted'
  /schedule/job/{id}:
    get:
      description: Get job status
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            format: int64
          required: true
          description: ID of the job
      responses:
        200:
          description: Job status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobStatus'
        '404':
          description: Not found
          content: { }
components:
  schemas:
    YoutubeChannelExists:
      description: Error
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: error message
    Status:
      description: Service status
      type: object
      properties:
        uptime:
          type: string
        docker_tag:
          type: string
          description: tag of the docker image
    YoutubeChannel:
      description: Youtube Channel
      type: object
      required:
        - name
        - youtube_id
      properties:
        id:
          type: integer
          format: int64
          description: internal id
        name:
          type: string
          description: channel name
        youtube_id:
          type: string
          description: youtube uniq
        created_at:
          type: string
    YoutubeChannelStatistics:
      description: Youtube Channel statistics
      type: object
      required:
        - id
        - statistics
      properties:
        id:
          type: integer
          format: int64
          description: internal id
        youtube_id:
          type: string
          description: youtube uniq
        statistics:
          type: array
          minItems: 0
          items:
            type: object
            required:
              - date
              - subscribers
            properties:
              date:
                type: string
                format: date
              subscribers:
                type: integer
                format: int64
                description: amount of subscribers
    StatGenerationStarted:
      description: Generation started
      type: object
      required:
        - statusPath
      properties:
        statusPath:
          type: string
          description: path for requests about status of the generation task
          example: /schedule/job/1
    JobStatus:
      description: Job status
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: integer
          format: int64
          example: 1
        total:
          type: integer
          format: int32
          description: total amount of channels in job
        ready:
          type: integer
          format: int32
          description: amount of handled channels in job
        error:
          type: integer
          format: int32
          description: amount of channels handled with error
        status:
          type: string
          enum:
            - NEW
            - RUNNING
            - ERROR
            - COMPLETE
    YoutubeChannelList:
      description: List of Youtube channels with pagination info
      type: object
      required:
        - currentPage
        - pageSize
        - totalPages
      properties:
        currentPage:
          type: integer
          format: int
          description: Current page number
        pageSize:
          type: integer
          format: int
          description: Number of items per page
        totalPages:
          type: integer
          format: int
          description: Total amount of pages
        channels:
          type: array
          items:
            $ref: '#/components/schemas/YoutubeChannel'