apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: ghcr.io/sergey-podunov/youtube_tracker
    newTag: latest

replicas:
  - name: youtube-tracker
    count: 2

patches:
  - path: cronjob-patch.yaml
  - path: deployment-patch.yaml
  - target:
      kind: Ingress
      name: youtube-tracker
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: youtube-tracker-prod.local
  - target:
      kind: Deployment
      name: youtube-tracker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/6/value
        value: "20"
      - op: replace
        path: /spec/template/spec/containers/0/env/7/value
        value: "5"
