---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret-config
  namespace: default
spec:
  encryptedData:
    password: AgB543PiCG2qAuENt/IblZ15RyUM8aJTUhWJvwvEDbGstcQQhib57we3rqqA/XLy+YOdOgRjEWX+bv8u0sgGgg5XcOtj5H0sODV9ggAPrdYsLAEf7TvPMD3iX7ga8mNYnM77XeERYaJMzSJ7uvSNhwP12MPB+0I7LFnl2F8cQV9dN5vmQlxo3D8G+L1B+gVmMBDXqvfqiG083RO7r5bTuTzp9YwUZYg+KW7MmTV47Kajca48LKtMryKCRpRfYLSbQA/wPc3eZBCrTz/M5eH91gNGv8JUElHMY91YD7pkqvzsimPwNOJEA8O+zVmxzpqUUXH6FPP1GnWCpkV2TvCk5v+8rqPSyUb7dQ7qGbBfnlb+Y1NZ3uOkTklGiDCyS8ue8lVsWdana/oSMo/aIXqSHey/NoxdUKmKKh7++0xRoKx5IjfraxKXxbllPneH0NveAO8/2ehxUUdD5yc5uJ8/PXzs3qbgRi+cmstfBKWWX6j6YvM5CVVjJGVv/V7UzZoBycf8g9WGei1fR1RPrCwt835ZSA4suVb0RNvsg49vrdM9Bie/7349/RVaTWSzrQ+WDPc3k3BGqAMdXcgqFtRnftHuptOVlhbn+8/FsgSwmJN15QkHDHpP866b+UstZBIUL7awssxYjOmC1cPt8xMv/6Y8yd9GljssbZjvCuE07WH87p8VMGK7EjY4uEc/VL3mANL/uLQsZBmAJ3Fkog==
    url: AgB8o72Eq3DBOIySWtjJaGgIMPUBu7aOWi2q0Wwp1hwOyUmi/tpRvf8jZNBr6ZlCyrAMS8d1g1MugnKgg8WS7M5f1hZEQVwzyCp+GzXX8ALtfW8YrYOJ2TVLGnCjdO6RmWRo/QcJIagNeo3zcYhCuo/+7AG7IeS0jtWBcSeJvgmnHFLjCkDeeSQbwH9yJIJCxW5zmH5vGJM7Vm+9PxIWndEYhvWoB1jNSzLih57U8CmNrlRSObmbwfqAMYJDE7IlDIQp1b87puU94rYk5ZeigsPnthbE1c/GZYjLwtfnchW/r9zETaz3kPQyEZg4B46QdU4vFeK+FFWmjGyE6k+YhkHzrhxY67xbmsb+dQ2Ddv4PeJP3q/9lh1MvBP5/jjQBSttp9yeSgSHyKv4R7yht621LNOD0HN5GzWTRErjfJ80tvS3RiBCNg/U3RHDneOcZx5SUdCtsWt6ecm44kHpgnu+wkdQodUDAjQcaPggVUJZJZ8vJq9tX7iXLu8DYSzyPc/Lvx/zfBfi5uFHLmcqDbbSGVvTrDIDsT6UJWRN8YCVTjlOnxiJMHFPPD07+TJh10ecH9vK1FcRWRYsuH3vqdMIPRUYkub+LRvnhjbK5e4Li+NxWHKZx+L2xFlVDmxoib/k9atm7GI0vnqe/F4Ys+sn9+jzBqy/6Hd/XEoUTZUWl3AYe/ajwu3Bp8+F4u/wPUHUMLBkWsNndyUmlxau/JjAdKa1I9d7A1RonIsG0Vka0SXtTypaz8yNMzQgrPCW266Fp0dshTeWrbDpWbI34a23vK9c=
  template:
    metadata:
      name: postgres-secret-config
      namespace: default
    type: Opaque
