### GET books

GET {{url}}/status

### store channel
POST {{url}}/youtube/channel
Content-Type: application/json

{
  "name": "@BBCNews",
  "youtube_id": "UC16niRr50-MSBwiO3YDb3RA"
}

> {%
    const responseBody = response.body;
    client.global.set("channel_id", responseBody.id);
%}

### get channel by id
GET {{url}}/youtube/channel/{{channel_id}}
Accept: application/json

### get channel statistics
GET {{url}}/youtube/channel/{{channel_id}}/statistics
Accept: application/json

### schedule statistics job
POST {{url}}/schedule
Accept: application/json

> {%
    const responseBody = response.body;
    client.global.set("job_path", responseBody.statusPath);
%}

### schedule job status
GET {{url}}{{job_path}}
Accept: application/json
