apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra-nginx-ingress.yaml
  - infra-atlas-operator.yaml
  - infra-sealed-secrets.yaml
  - infra-base.yaml
  - app-atlas-schema.yaml
  - app-sealed-secrets.yaml
  - app-youtube-tracker.yaml