apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtube-tracker
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: youtube-tracker.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: youtube-tracker
                port:
                  number: 8080
