apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: youtube-tracker-root
    patch: |
      - op: replace
        path: /spec/source/path
        value: k8s/argocd/templates/overlays/prod