---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notify-secrets
  namespace: default
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: AgArPSnnBd0SFtLNx2GXSOcYNLG8mYFAGy++YiEwTE3WIUOUvjgOvYzUU4ucexxnl6ZwhBI15L2AxYzmF6LtObjQTmIrYnJVDYPRl8nRvuzb7CHn367xBV0LPm7bhATx/w/+sRJ4xLowgHAw1uJr+FY0ZRnYgB1mZOWTEfzkP0OsZ47P++qFl/RQMe1bhA1RZCvewcH3+4Dk9sQAXV/BKSTODzXgMvPNQBP8CUFzJWHeg3AHYFno7iJ6JHSmJlaw35KlRFlsYFixrU1SlBARVm4VGdsrwiGkIa6/K27EC1lLd/wqLlulertINm1Ae+QDYzswExT3oFEPlhOQcw1tLp3+x/F/AE0wPzxRmZsGGhvdWmRKf06eecuzJ0F4MFPKkQc3XjlPzXjm39qJHLYzz1dcNpJVS4ku2FS0R+Lc6He+jTuBhNL+vqKnyDqP9+oEy5XD+9v9M68s4qvvsPhj5G8VvsEhi/Fvr07MKWNnLlDG+7QxdluBJTsX7CN7uj0UJIxsNPI4n7nVw6PYRzC7Gj0CDdopI48rq8gZdoR2SMm19s/s6KPjC4JxRxv7V93wrkma6W8YCwxMo0ZOyFt0FQGnxDILnChO0R8LRdFqNJcKADhqIhe+DFKhmQdYUv/uWLUu4dmeYAhSksrpy+7QRd2zerjIkcSq3MnAZCsrppIFdV0oJlR5OPrARePPjf+fC+HxkJ+SZj/Gt1SIJUd0JcZAquBZbamW82LMjqlc/nZwueqEdaVdXOjRFXBKYp06VrbNImUdbpEcYjAUL52ccTVACXRyMCvKUOr0ynCA2pyMFy4=
  template:
    metadata:
      name: notify-secrets
      namespace: default
    type: Opaque
