---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: google-api-key
  namespace: default
spec:
  encryptedData:
    api-key: AgB/aoHdzBU8820h8ShdIlTMIuGBLWOjgcyZ0BxvOF7Slmaz6kMrATjte2E1EYAW4egIMx9WKTFpvROdWuCv543nzXfJUvMdm80BC+QZtEIjJ44OReFJ+1lWZUmPdL+wEboeETNc7WUPNCnJBDwnXGJRM8fvxRaJF1heWjCqPu/AQgb1WiuCpxxtRD0rJYf+EQNlsWAkHX9qNLiQ5NtHG5pK+W79T2daSOM4pLp+UU08KiAPSVSy264+fNbWT5O5mQtlq4Gzokmx4KCrN/96/KVvZ6U9z2N5PqC+K/zH8XJdK8wSsleEnhQFoED8+XQm8BcO1oOWEHMTLGZ3Ujb9JmQY9Mbid2btsSvV7LSZX9r4Lee/l7M+wg8St4lRAeGX7XONqqCjl7oe8VBLlVTwZ/008wVl6KYQcciNV+ldr6TrW9yW4yNqfqAPp7focfWD0toQiiwCuADoONjNTA98j1dluZ2DcNGQ3itCF/zt+2a4CzZaRLNFdKSx1jPyX4VlpZrT1JoeXflsGd3XxTYnFmSvtENR11lpbMIF5N2GezxLHntPI+WaHTiAvDH7ojYzN2JVxwa6jhF9U+Ib4F8QJ4tHNayq9S27RyIuyOP+Ib2McO3RGA1o3HCWmXVQzzYxpub9lYWfws1gTaR5HRrLQLJkcIuDOFaiMhm5kzGSaqt7DbJygyKbDNPzMCNFTl4SWcg6OZZLLkHEQ5dgPh2j9pjAJIFfiCPG+K1Wgvi0b2zQDsUX5BMGj1Y=
  template:
    metadata:
      name: google-api-key
      namespace: default
    type: Opaque
