---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCJ2KbwdFPTnlnwsBIwFl8H+nbNHjaetDBGS7Be918WBsT01kZHUbK/2gm59oYGR7rGyCTwtqOMaRdN12RWiSu0Ld3i04jwuYRQp3xEfJ6xitHUmNa3j7RulNyJERh9Lt04LVVRiFnRqUEhmTZMYmaso6jXbiqdiZWyycfcZdojyVBfd2CWNUVu2bfvl/w9ET6zyznNGcAM7nsvB2RsLJUmFKDz+wc2ni7A7WPsbGsA4u6/ugPqIEjeMKUn96tEf0Zle2kkbWnxEgKBFbmSCUpiKG4H7eqixs/rKiUmpDMCQ6GXhrjyQEr5PhcSCA4eZCCRykeF03lLWKT/NUjymVh/zRD2teXOc+XjWF4cpJcNEdUqnAoNn9HNDz+Qq2tSU03qhEMLzwvIsqRqo4Z0m/DuKEIRsLpAvQKekuifhxOY2iZetRE0gLFOpTMMkpKH/Qf/19PQLFOzA6ICP6dJC2GLp+8xql+7GYX3q5wWvrARfimgAKl8C33I09i+AIOaF31clF4LKcaPuchOXSQHh+SEC+NVqZl65VI5jFBX+nfj68UL64vqE4vwBSdLeMEVI9LB6SiiqpslmrokPxrmQrTzofajSiwMkldbqT5FlgRh5Ldmi3PEwE0oHqEhhpKOMZw56O6dVjqMNqPAiFzXI4SeZ05/vsJX3/3tJJBwTcV30/GkCqTjkbFuY+HlJmua8zGtn9LozRJFPtE//EqrykyWuGxXhOAA36GBpZVNr9q7YrfrOW1dqdtjb0vDPoWtE7gXpt7nkvbN6/YbIiaZCswvV7eBXFIlqPaz0V38SJZA7d+v7nNmURqbe5Ym6F+MlinKOSi8odr+vr6qigbgp06YyhDpuVzdxxhRLhp3BOxCRiT6qGomhMew2mLLNU+DKjVBBK6cDMA/4NgWzX1a1bnGvns42NfNK/aBiSOmLETuHCpGT6tyTeHB5vkQ7FeGhWm3G2kY4862Zb1hdrmIAp7nvq7miz2Y3+h8CxFr1328mV9J
  template:
    metadata:
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
