apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: youtube_channel
  namespace: default
spec:
  database: psdb
  name: youtube_channel
  schema:
    postgres:
      primaryKey:
        - youtube_channel_id
      columns:
      - name: youtube_channel_id
        type: serial
        constraints:
          notNull: true
      - name: external_id
        type: varchar(125)
        constraints:
          notNull: true
      - name: channel_name
        type: text
        constraints:
          notNull:
            true
      - name: created_at
        type: timestamp without time zone
