CREATE TABLE youtube_channel (
          youtube_channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          external_id VARCHAR(125) NOT NULL,
          channel_name TEXT NOT NULL,
          created_at TIMESTAMP WITHOUT TIME ZONE
      );
      CREATE TABLE youtube_channel_stat (
          youtube_channel_stat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          youtube_channel_id BIGINT NOT NULL,
          created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
          subscribers_count BIGINT NOT NULL,
          FOREIGN KEY (youtube_channel_id) REFERENCES youtube_channel (youtube_channel_id)
      );